kubeConfig: .kube/config
auditEnabled: true
auditDir: audit_output
cucumberDir: cucumber_output
overwriteHistoricalAudits: true
summaryEnabled: true
imagesRepository:
azure:
    subscriptionID:
    clientID:
    clientSecret:
    tenantID:
    locationDefault:
probes: # this entire object can be left out if all tests are to be run
  - name: account_manager
    excluded: false
    justification: "demo"

  - name: container_registry_access
    excluded: false
    justification: "demo"

  - name: general
    excluded: false
    justification: "demo"
    scenarios:
      - name: CIS-5.6.3
        excluded: false
        justification: "scenario exclusion demo"

  - name: iam_control
    excluded: false
    justification: "demo"

  - name: internet_access
    excluded: false
    justification: "demo"

  - name: pod_security_policy
    excluded: false
    justification: "demo"
    scenarios:
      - name: AZP-0.3
        excluded: false
        justification: "scenario exclusion demo"
