apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels: 
    caller: {{ probr-caller-function }}
    feature: k-psp-011
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/unapproved-profile.json"
spec:  
  securityContext:
    runAsUser: 1000    
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]      
  containers:
  - name: psp-azp-seccomp-unapproved
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: {{ probr-cap-drop }}