# Empty and omitted keys will use default values
AuditEnabled: true
AuditDir: audit_output
CucumberDir: cucumber_output
OverwriteHistoricalAudits: true
ServicePacks:
  Kubernetes:
    Excluded: # "justification for exclusion" # any non-empty value here will exclude all elements within the service pack
    KubeConfig: 
    KubeContext:
    AuthorisedContainerRegistry: citihubprod.azurecr.io
    UnauthorisedContainerRegistry: docker.io
    ProbeImage: citihub/probr-probe
    Probes: # allows this pack's probes to be disabled by name
      - Name: pod_security_policy
        Excluded: "yes"
      - Name: iam
        Excluded: ""
      - Name: general
        Excluded: "yes"
      - Name: container_registry_access
        Excluded: "yes"
      - Name: internet_access
        Excluded: "yes"
        Scenarios: # allows this probe's scenarios to be disabled using their probe tag value
          - Name: "1.0"
            Excluded: # "Excluded to demonstrate scenario exclusion option"
  Storage:
    Excluded: "not yet fully implemented" # any non-empty value here will exclude all elements within the service pack
    Probes: # allows this pack's probes to be disabled by name
      - Name: access_whitelisting
        Excluded:
      - Name: encryption_in_flight
        Scenarios: # allows this probe's scenarios to be disabled using their probe tag value
        - Name: "1.1"
          Excluded:
CloudProviders:
  Azure:
    TenantID:
    SubscriptionID:
    ClientID:
    ClientSecret:
    ManagementGroup:
    Location:
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Tags: # allows user to create their own string of tag inclusions and/or exclusions
TagExclusions: # allows specific controls/scenarios to be disabled via a list of tags
