AuditEnabled: true
AuditDir: audit_output
CucumberDir: cucumber_output
OverwriteHistoricalAudits: true
SummaryEnabled: true
ImagesRepository:
ServicePacks:
  Kubernetes:
    KubeConfig: .kube/config
    KubeContext:
CloudProviders:
  Azure:
    SubscriptionID: 1234
    ClientID:
    ClientSecret:
    TenantID:
    LocationDefault:
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Probes: # this entire object can be left out if all tests are to be run
  - Name: account_manager
    Excluded: true
    Justification: "demo"

  - Name: container_registry_access
    Excluded: false
    Justification: "demo"

  - Name: general
    Excluded: false
    Justification: "demo"

  - Name: iam_control
    Excluded: false
    Justification: "demo"

  - Name: internet_access
    Excluded: false
    Justification: "demo"

  - Name: pod_security_policy
    Excluded: false
    Justification: "demo"
